build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140

complexity:
  LongParameterList:
    functionThreshold: 8
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']
  CyclomaticComplexMethod:
    ignoreAnnotated: ['Composable']
  ComplexCondition:
    threshold: 5

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
    excludes: ['**/commonTest/**', '**/androidTest/**', '**/test/**']
